# echo -n 'postgres' | openssl base64
apiVersion: v1
kind: Namespace
metadata:
  name: prgs
---
apiVersion: v1
kind: Secret
metadata:
  name: prgs-k8s-superuser
  namespace: prgs  
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prgs-k8s
  namespace: prgs  
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised  
  enableSuperuserAccess: true
  storage:
    size: 1Gi
  managed:
    roles:
    - name: prgs-docker
      ensure: present
      comment: User prgs-docker
      login: true
      superuser: true
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 300
  bootstrap:
    initdb:
      import:
        type: monolith
        schemaOnly: true
        databases: 
          - prgs-docker
        roles:
          - prgs-docker
        source:
          externalCluster: docker
  superuserSecret:
    name: prgs-k8s-superuser
  externalClusters:
  - name: docker
    connectionParameters:
      host: 192.168.100.3 
      user: postgres
      dbname: prgs-docker
    password:
      name: prgs-k8s-superuser
      key: password
      
